Wait until ImageFound(text:"More", waitFor:2, validWords:"*", SearchRectangle:HandlerGarage.ScreenPart("HyperspaceToolbar")) or ImageFound(text:"Log Out", waitFor:1, validWords:"*", SearchRectangle:HandlerGarage.ScreenPart("HyperspaceToolbar"))

If ImageFound(image:"HighContrastColorSwatch")  is false then
	HandlerGarage.OpenEpicMenuItem "Look and Feel"
	Wait 1
	Click text:"High Contrast", waitFor:2,SearchRectangle:HandlerGarage.ScreenPart("StoryBoard")
	TypeText controlKey,"q"
End If
